### ISSUE TITLE
NEF_emulator "marketing"

### ISSUE THREAD

**Issue by tgogos** [medianetlab/NEF_emulator#30]
Σε αυτό το issue θα μπορούσαμε να συντονιστούμε λίγο για το πλασάρισμα του NEF_emulator.

**Tasks για το github**:

 - [x] short description για το "about" του repo
 - [x] προσθήκη topics (πχ `5G`, `NEF` κλπ...)
 - [ ] description + καμιά φωτό για να προστεθεί πάνω-πάνω στο README

**Dashboard - UI**:
 - [ ] προσθήκη Copyright
 - [ ] προσθήκη logos?

**Landing page**:

 - [ ] μία επιλογή εδώ ίσως θα ήταν μέσω των github pages, το URL θα είναι της μορφής: https://medianetlab.github.io/NEF_emulator
